"""ingestion schema — append-only trigger backstop on evidence + custody (ADR-0004, part 3).

Adds ``BEFORE UPDATE OR DELETE`` triggers that ``RAISE`` on ``ingestion.evidence`` and
``ingestion.evidence_custody_events``, so evidence rows and their custody ledger cannot be mutated
or deleted at the database layer. Defense-in-depth beneath ADR-0004's role-level ``REVOKE`` and
ADR-0003's anchored ledger. The DDL is generated by ``platform.db.append_only`` (the exact SQL
proven by ``tests/integration/test_append_only_db.py``).

Revision ID: 202607280002_ingestion_append_only
Revises: 202607210002_ingestion
"""

from __future__ import annotations

from alembic import op

from sentinelai.platform.db.append_only import (
    create_reject_function_sql,
    create_trigger_sql,
    drop_reject_function_sql,
    drop_trigger_sql,
)

revision = "202607280002_ingestion_append_only"
down_revision = "202607210002_ingestion"
branch_labels = None
depends_on = None

_SCHEMA = "ingestion"
_TABLES = ("evidence", "evidence_custody_events")


def upgrade() -> None:
    op.execute(create_reject_function_sql(_SCHEMA))
    for table in _TABLES:
        op.execute(create_trigger_sql(_SCHEMA, table))


def downgrade() -> None:
    for table in _TABLES:
        op.execute(drop_trigger_sql(_SCHEMA, table))
    op.execute(drop_reject_function_sql(_SCHEMA))
