"""platform schema — append-only trigger backstop on audit_log (ADR-0004, part 3).

Adds a ``BEFORE UPDATE OR DELETE`` trigger that ``RAISE``s, so ``platform.audit_log`` rows cannot be
mutated or deleted at the database layer. Defense-in-depth beneath ADR-0004's role-level ``REVOKE``
and ADR-0003's anchored ledger. The DDL is generated by ``platform.db.append_only`` so it is the
exact SQL proven by ``tests/integration/test_append_only_db.py``.

Revision ID: 202607280001_platform_append
Revises: 202607210001_platform
"""

from __future__ import annotations

from alembic import op

from sentinelai.platform.db.append_only import (
    create_reject_function_sql,
    create_trigger_sql,
    drop_reject_function_sql,
    drop_trigger_sql,
)

revision = "202607280001_platform_append"
down_revision = "202607210001_platform"
branch_labels = None
depends_on = None

_SCHEMA = "platform"
_TABLES = ("audit_log",)


def upgrade() -> None:
    op.execute(create_reject_function_sql(_SCHEMA))
    for table in _TABLES:
        op.execute(create_trigger_sql(_SCHEMA, table))


def downgrade() -> None:
    for table in _TABLES:
        op.execute(drop_trigger_sql(_SCHEMA, table))
    op.execute(drop_reject_function_sql(_SCHEMA))
